source: ./source
destination: ./_build
layouts: ./_layouts
timezone: America/Chicago
markdown: rdiscount
highlighter: pygments
permalink: /blog/:title
url: http://johnkary.net
baseurl: /
show_drafts: true
